### ISSUE TITLE
class 'Vinkla\Pusher\Facades\Pusher' does not have a method 'socket_auth'

### ISSUE THREAD

**Issue by Clem01** [vinkla/laravel-pusher#17]
Hello,

I don't arrive to implementing the auth endpoint for a private channel. The response is: class 'Vinkla\Pusher\Facades\Pusher' does not have a method 'socket_auth'

My code:
```
class UserController extends Controller
{
    protected $pusher;

    public function __construct(PusherManager $pusher)
    {
        $this->pusher = $pusher;
    }
    
    public function getAuthPusher()
    {
        $auth = $this->pusher->socket_auth($_POST['channel_name'], $_POST['socket_id']);
    }
}
```

Thank you for your help :)

**Comment by GrahamCampbell** [comment]
It has a __call method.

**Comment by GrahamCampbell** [comment]
well, call static

**Comment by Clem01** [comment]
Thanks for your quick response! Can you give me an example please ?

**Comment by GrahamCampbell** [comment]
No, just call the method?

**Comment by GrahamCampbell** [comment]
It doesn't need to exist to be called.

**Comment by Clem01** [comment]
I do not understand how to call the method "socket_auth".
I try: $auth = $this->pusher->socket_auth;

**Comment by GrahamCampbell** [comment]
Should work just fine?

**Comment by Clem01** [comment]
No, it does not work: 'ErrorException' with message 'Undefined property: Vinkla\Pusher\PusherManager::$socket_auth'

Finally I found a solution ... less clean but it works:
```
    public function getAuthPusher(Request $request)
    {
        $this->validate($request, [
            'channel_name' => 'required',
            'socket_id' => 'required',
        ]);
        
        $options = array(
            'cluster' => config('pusher.connections.main.options.cluster'),
            'encrypted' => config('pusher.connections.main.options.encrypted')
        );
        $pusher = new \Pusher(
            config('pusher.connections.main.auth_key'),
            config('pusher.connections.main.secret'),
            config('pusher.connections.main.app_id'),
            $options
        );
          

        $auth = $pusher->socket_auth($request->channel_name, $request->socket_id);
        
        ...
    }
```

**Comment by GrahamCampbell** [comment]
> No, it does not work: 'ErrorException' with message 'Undefined property: Vinkla\Pusher\PusherManager::$socket_auth'

You need to call with with paramaters, instead of using property access. Your code there is not right.

**Comment by GrahamCampbell** [comment]
> $this->pusher->socket_auth($request->channel_name, $request->socket_id);

That there WILL work just fine.

**Comment by Clem01** [comment]
I just found the problem !!

I added the alias 'Pusher' => Vinkla\Pusher\Facades\Pusher::class,
I removed it and it works now :)

Thanks for your help !
