### ISSUE TITLE
I can not install this package in laravel 5.4

### ISSUE THREAD

**Issue by phuongphally** [vinkla/laravel-pusher#21]
c:\xampp\htdocs\mymusic (master)
λ composer require vinkla/pusher
Using version ^2.4 for vinkla/pusher
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - vinkla/pusher 2.5.0 requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
    - Installation request for vinkla/pusher ^2.4 -> satisfiable by vinkla/pusher[2.4.0, 2.5.0].
    - Conclusion: remove laravel/framework v5.4.15
    - Conclusion: don't install laravel/framework v5.4.15
    - vinkla/pusher 2.4.0 requires illuminate/contracts 5.1.* || 5.2.* || 5.3.* -> satisfiable by illuminate/contracts[v5.1.1, v5.1.13, v5.1.16, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/contracts v5.1.1|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.1.13|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.1.16|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.1.20|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.1.22|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.1.25|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.1.28|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.1.30|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.1.31|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.1.41|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.1.8|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.2.0|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.2.19|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.2.21|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.2.24|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.2.25|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.2.26|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.2.27|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.2.28|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.2.31|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.2.32|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.2.37|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.2.43|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.2.45|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.2.6|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.2.7|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.3.0|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.3.16|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.3.23|don't install laravel/framework v5.4.15
    - don't install illuminate/contracts v5.3.4|don't install laravel/framework v5.4.15
    - Installation request for laravel/framework (locked at v5.4.15, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.15].

Installation failed, reverting ./composer.json to its original content.

**Comment by vinkla** [comment]
You need to upgrade to PHP 7.0 before updating this package.

**Comment by YuriFontella** [comment]
And for those who already have installed php 7, as was my case ... it is necessary to change the file composer.json in:

``` bash
"Platform": {
  "Php": "7.1.8" //5.1.6
 }
```
In the config object.

**Comment by vinkla** [comment]
@YuriFontella no it isn’t necessary? If you have the correct version installed you don’t need to configure the platform.

**Comment by YuriFontella** [comment]
I do not know why, but in my composer.json it was 5.1.6. Then there was the same error described above by phuongphally.

**Comment by vinkla** [comment]
You are probably running an older version of PHP.

**Comment by YuriFontella** [comment]
My version was already version 7, even though the error was happening. I changed the platform from 5.1.6 to 7.1.8 and was able to do the installation.

I just reported that I saw that your solution was to have php 7. As I already had and it still had not worked. It only worked when I changed the platform in composer.json.

Thks @vinkla

**Comment by vinkla** [comment]
Okay, good. Out of curiosity: did it work when you removed the platform config?

**Comment by YuriFontella** [comment]
I did not remove it, I just changed the version that was there. I went to my terminal with the command php -v (7.1.8) and replaced with the version that was there. And so I was able to perform the installation.

``` bash
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true,
        "platform": {
            "php": "7.1.8"
        }
    }
```
