### ISSUE TITLE
config/pusher.php vs config/broadcasting.php

### ISSUE THREAD

**Issue by pedzed** [vinkla/laravel-pusher#23]
Is there really a `config/pusher.php` file necessary? What should we do with `config/broadcasting.php`?

It would be nice if this would be documented.

**Comment by vinkla** [comment]
Yes, `pusher.php` is required by this package and `broadcasting.php` is required if you want to use Laravel's broadcasting.

**Comment by pedzed** [comment]
Isn't it better to prevent config duplication by making use of `broadcasting.php`?

**Comment by vinkla** [comment]
> Isn't it better to prevent config duplication by making use of `broadcasting.php`?

Nah, since you might use this package without touching Laravel's broadcasting.
