### ISSUE TITLE
Pusher cluster for Cameroon-Africa

### ISSUE THREAD

**Issue by kamgasimo** [vinkla/laravel-pusher#25]
I saw in the documentation that the cluster where for specific regions or countries.
Is there a cluster for Cameroon an African country?
Or can we use the eu cluster?

**Comment by vinkla** [comment]
@luismfonseca can you answer this question?

**Comment by luismfonseca** [comment]
Hi @kamgasimo, 

We can boot new dedicated clusters in any AWS region. Unfortunately, they don't have any regions in Africa.

I suggest testing out our public clusters and see which one yields the lowest latency and go with that. :)

**Comment by vinkla** [comment]
Closing this since @luismfonseca has answered.
